server:
  port: ${PORT:8081}

spring:
  application:
    name: imgr
  mvc:
    servlet:
      path: /api
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/imgr}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:040799}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    show-sql: true

