server:
  port: ${PORT:8081}

imgr:
  app:
    jwt:
      secret: 040799Khoa
      expiration: 900000
spring:
  application:
    name: imgr
  security:
    filter:
      order: 10
    user:
      password: 040799
  mail:
    host: smtp.gmail.com
    port: 465
    username: blackparadise0407@gmail.com
    password: ${SMTP_PASSWORD}
    templates:
      path: mail-templates
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true
            required: true
  thymeleaf:
    prefix: classpath:/mail-templates
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/imgr}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:040799}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true


